### ISSUE TITLE
urls such as http://qcm.ffvl.fr/#/load/415550484197613036 redirect to http://qcm.ffvl.fr/#/qcm

### ISSUE THREAD

**Issue by OlivierPerceboisGarve** [jruffet/qcmffvl#6]
Hi Jérémy
for me, using chrome, urls such as urls  http://qcm.ffvl.fr/#/load/415550484197613036 
do redirect to the default url http://qcm.ffvl.fr/#/qcm

**Comment by jruffet** [comment]
Hi, sorry for the late reply.
This is the expected behavior, and QCM 415550484197613036 should be what is presented to you.
You can check the current QCM ID in "partager".

**Comment by jruffet** [comment]
Clicking "partager" should not erase anything.
Copy-pasting the URL in your browser address bar will trigger a reset of your answers.

This is the intended behavior, based on a limitation of the client-only approach : the QCM ID has all the infos to reconstruct the QCM, storing all the answers would generate an ID way too big.

I understand that it might not be obvious so I will update the text in this direction.
